### ISSUE TITLE
MRO_DISK_SPACE_CHECK

### ISSUE THREAD

**Issue by ascendo** [martian-lang/martian#10]
Of course, I did source my bashrc with export.

![image](https://user-images.githubusercontent.com/907041/47466308-8b36cc00-d7a5-11e8-9d58-3b776f4b6d89.png)

_Originally posted by @ascendo in https://github.com/martian-lang/martian/issues/9#issuecomment-432855673_

**Comment by adam-azarchs** [comment]
You are attempting to restart with a failed pipestance.  You're hitting a bug in martian 2.3.3 which was fixed in martian 3.0, where it's generating an `_errors` file in the top-level when it hits an error. You will need to delete `JG_Melinda_56x/ASSEMBLER_CS/_errors` in order to allow the pipestance to be restarted.

For assistance running 10X Genomics pipelines, please contact <support@10xgenomics.com>.  This issue tracker is for bugs in the current version of Martian only.
