### ISSUE TITLE
fatal: remote origin already exists

### ISSUE THREAD

**Issue by cdunn2001** [martian-lang/martian#11]
Before submitting an issue, be sure to read our [contribution guidelines](CONTRIBUTING.md)

## Component

`mrp`

## Pipeline

`martian/test/fork_test`

## Runtime environment
Include the full command line used to run the executable.

    mrp --jobmode=local pipeline.mro fubar

Include all non-sensitive environment variables.  We don't want to see user or host names.

Include the operating system distribution and version (include the output of `uname -a`).

    Linux harvey 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Especially for cluster mode jobs, include any relevant configuration files,
especially the job template in the `jobmanagers`.

For MRP issues, specify the filesystem you are running on (e.g. ext3, nfs backed by zfs, gpfs) if you know.

Much of this information and more is in the `sitecheck.txt` produced by 10X pipelines.

## Expected behavior

What did you want to happen?

## Actual behavior

```
mrp --jobmode=local pipeline.mro fubar
Martian Runtime - <version not embedded>
2018-12-02 09:37:50 [runtime] Reattaching in local mode.
Serving UI at http://mp0812-sge66:1818?auth=fRt32yI3qTmAymlodUg9Qv5D09ywzlkEXKD6RnWDKbI

2018-12-02 09:37:50 [runtime] (reset-partial)   ID.fubar.AWESOME.ADD_KEY1.fork0.chnk0
2018-12-02 09:37:50 [runtime] Found orphaned local stage: ID.fubar.AWESOME.ADD_KEY1
Error starting web server: open /home/UNIXHOME/cdunn/repo/gopath/web/martian/templates/graph.html: no such file or directory
2018-12-02 09:37:50 [runtime] (split_complete)  ID.fubar.AWESOME.ADD_KEY1
2018-12-02 09:37:50 [runtime] (run:local)       ID.fubar.AWESOME.ADD_KEY1.fork0.chnk0.main
2018-12-02 09:37:53 [runtime] (failed)          ID.fubar.AWESOME.ADD_KEY1

[error] Pipestance failed. Error log at:
fubar/AWESOME/ADD_KEY1/fork0/chnk0-u350c04186e/_errors

Log message:
Error starting job.

fork/exec /home/UNIXHOME/cdunn/repo/gopath/adapters/python/martian_shell.py: no such file or directory
```

I don't understand the path. Under `/home/UNIXHOME/cdunn/repo/gopath/` I have `src/github.com/martian-lang/martian`.

I installed as mentioned in the README:

```
$ go get github.com/martian-lang/martian/cmd/mrp
$ go install github.com/martian-lang/martian/cmd/...
$ cd ${GOPATH}/src/github.com/martian-lang/martian/web && npm install && gulp
```
(Well, almost. I think that's wrong. You have to run `npm` from the directory with `package.json`, which is actually `src/github.com/martian-lang/martian/web`. And I had to run `node_modules/gulp/bin/gulp.js`, since I could not find `gulp`.)

Also, because of the path problem, I copied `config.json` into my `$GOPATH` directory. But I can't get past the others.

So I'm trying to install by the other instructions in the README:
```
$ git clone https://github.com/martian-lang/martian.git --recursive
$ cd martian
$ make
```

That's where I hit `fatal: remote origin already exists`.
```
$ make grammar
PATH=/home/UNIXHOME/cdunn/repo/gopath/src/github.com/martian-lang/martian/bin:...  go generate -v github.com/martian-lang/martian/martian/syntax
Fetching https://golang.org/x/tools?go-get=1
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
get "golang.org/x/tools": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
get "golang.org/x/sys": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys?go-get=1
go: github.com/cloudfoundry/gosigar@v1.1.0: git remote add origin https://github.com/cloudfoundry/gosigar in /home/UNIXHOME/cdunn/go/pkg/mod/cache/vcs/430bfd40e6b6dee4f9f29b15808b29f857ddc83672f584167cde80f467fc5f0f: exit status 128:
        fatal: remote origin already exists.
(and same for 3 other repos)
```
I tried removing `/home/UNIXHOME/cdunn/go/pkg/mod/cache`, but it just happens again.

Please help!
```
```

**Comment by adam-azarchs** [comment]
This is two separate bugs.

The first issue is a documentation flaw.  `mrp` looks for various files relative to where its own binary is located, and it expects to be located in it's repository directory's `/bin` directory.  The `Makefile` does that by setting `GOBIN=$(shell pwd)/bin`.  It also unsets `GOPATH` because go modules don't seem to play nice with `GOPATH`.  I'll update the documentation.

The second issue appears to be a conflict between go's module fetching and `go get`'s.  I'd say this looks like a bug with go, actually, although one might be expected to run into issues you're using `GOPATH` inconsistently like that.  You might try deleting `$HOME/go/src/github.com/<repo>` for each repo which is causing problems.  Possibly also `GOPATH= go clean -modcache`.

**Comment by cdunn2001** [comment]
Moving the `bin` worked. `fork_test` passed!

Someday, I'll experiment with `GOPATH` and let you know if I learn anything.

2 other questions:

1) I like to use `git` to record the state of a previous run, and then re-run in the same directory. I `git add` all, commit, and then erase everything except the `.git` directory. Martian complains:
```
mrp --jobmode=local pipeline.mro fubar
...

cd fubar
git init
git add -A .
git commit -m 'init'
rm -rf *
cd ..
mrp --jobmode=local pipeline.mro fubar

RuntimeError: .../martian/test/fork_test/fubar is not a pipestance directory
```
Is there a way around that? Apparently Martian is fine with a completely empty directory.

2) `fork_test` takes 15s (prior the 6s wait for the UI). Why 15s for a completely local run? Can that be sped up?

**Comment by adam-azarchs** [comment]
1.  My recommendation here would be to run the pipeline in a sub-directory of the git repository.  That is, leave out the `cd ..` step.  Martian expects a pipestance directory to be either completely empty or to include an `_invocation` and `_mrosource` file.  This is because with an existing directory the assumption is that you're trying to restart an existing pipeline.  Completely empty existing directories are [allowed](https://github.com/martian-lang/martian/blob/5a8a16bb8a648e7b2d92cc32a9ba48fbc6600de2/martian/core/runtime.go#L414) as a special case, to enable a use case that we have quite a bit internally, where we run a pipestance in a directory that is a symlink to another location (specifically, we have a long-term storage location on relatively inexpensive spinning disks, and put a symlink there to fast flash drives to run pipestances, then move the pipestance to the slow disk when done).  I think it would be reasonable to change the logic to ignore files or directories with names beginning with `.` (hidden files/directories, at least on unix systems) for purposes of determining if the directory was empty.

A couple general comments on attempting to compare pipestances with git that way.  First, you should probably exclude the `files` directories, since those often include very large input or output data files, and git doesn't handle those very well.  Second and perhaps more critically, comparisons of anything besides the top-level outputs and metadata will be difficult because martian runs jobs in a uniquely-named directory every time.  This feature is intended so that if you run a cluster-mode job, abort, delete the pipestance directory, and then re-run, a queued job on the cluster from the previous run won't accidentally overwrite the output for the new run.  git may or may not properly detect the rename.  If you don't care about that stuff, I'd recommend adding the entire `PIPELINE_NAME` subdirectory of the pipestance to `.gitignore`.  If you do care, you'll probably need to do something more advanced for comparing runs, or set `MRO_UNIQUIFIED_DIRECTORIES=disable` in your environment.

Also, if you want to rerun pipelines with different arguments, you may want to consider using martian's the [`sweep` feature](http://martian-lang.org/advanced-features/#parameter-sweeping) to run the different versions in parallel.  That has the advantage of not duplicating work for stages which don't take the swept-over parameter as input (and don't depend on a stage which does).  Obviously that doesn't help unless you know in advance what you want to change, but it's great for integration tests.

2.  `mrp` polls the filesystem for updates every 3 seconds.  If the critical path for the pipeline has 5 stages, that's up to 15 seconds total of time spent between when a job finishes and when `mrp` notices that it finished.  Theoretically, for local jobs, `mrp` could poll immediately when it saw its child process terminate.  However it can't do that easily for cluster mode jobs.  While such a change would make a big difference for a toy pipeline like `fork_test`, most real-world pipeline stages take at least several minutes to run, so the benefit would be small.  Our internal pipeline authoring guidelines discourage breaking jobs up at a finer granularity than that because in cluster mode the per-job overhead would dominate for such short jobs.  That makes this a low-priority optimization, but something I'll consider adding next time I have time to work on that corner of the code.

**Comment by adam-azarchs** [comment]
Documentation for checkout and build has been updated in d95155af175acc80841eeb5b157f961b0a3f16c7.  Please open separate issues if you have further questions.

**Comment by cdunn2001** [comment]
Thanks for the very interesting info and good ideas.

If we adopt Martian, I'll want to use a quick initial polling rate for `mrp`. It can back-off quickly. I use very small synthetic/simulated testdatasets, and I like to run quickly locally first, to check integration.

I like *Martian* a lot. The `split/main/join` very similar to what I've done in my own projects. [More commonly](https://en.wikipedia.org/wiki/MapReduce) it's called the `split-apply-combine strategy`. It's a nice happy medium between a fully dynamic DAG and the restrictive chunking that is typical of most workflow-engines. But I need to convince management.

One thing that could help: Support for "Common Workflow Language" (for simpler pipelines). Have you considered that? Would you accept a pull-request for that?

One potential problem: I have seen many problems with filesystem polling, the worst being high filesystem latency. (I've measured up to 20s and inferred as much as 40s.) I thought in cluster-mode, `mrp` actually called the `query` command. No?

(It could be nice if `mrp` watched for the `pid` in local-mode, but filesystem-polling is more reliable locally anyway.)

**Comment by adam-azarchs** [comment]
We've thought about integrations with CWL.  It hasn't been a priority for us yet, but I could see it getting there, especially as we'd like to enable people to integrate our pipelines with their preexisting ones.  We'd need to discuss internally what such an integration would look like - my first spitball would be essentially an CWL to MRO "transpiler" of some kind but I haven't had a chance to look into it more deeply.

Yes, filesystem latency can be significant.  That is, in fact, why we depend on filesystem polling rather than querying the job manager (e.g. `qstat`) - we want to be reasonably certain that the output files from precursor jobs are visible to any follow-on tasks before we start them.  We do poll the job manager in case the job failed without writing output, but we've seen customer systems with tens of minutes between when the job completes and when its output files become visible to other nodes, and it isn't safe to start subsequent jobs until then (and even then it's only safe to the extent that the filesystem honors total store ordering, which most don't, at least formally).  From experience, we actually put in a default grace period of 50 minutes between when the job manager says the job finished and when we declare the job failed if no output shows up (the actual latency varies tremendously based on site configuration and hardware).  Again, though, that latency is usually a minor factor for larger pipelines.

Of course in local mode I don't know of any filesystems which would have visible latency there, and it should be pretty straightforward to make the polling loop trigger early when a local child process finishes.  For cluster mode, most job management systems I've had occasion to use (SGE and LSF mostly) have at least a few seconds of scheduling latency so I don't really see polling more often than 3 seconds being likely to make much difference.  We have been thinking of adding a feature to allow stages to declare an estimated run time (per split/chunk/join), as some job schedulers can make smarter packing decisions with that information, and because having progress bars is nice.  If we did that then I could see doing quicker polling if you launched a stage with a very short estimated runtime.  I wouldn't want to otherwise, however, since stressing out the NFS server with extra metadata queries could be counterproductive.

**Comment by adam-azarchs** [comment]
Let me see if I understand your suggestion correctly:
1.  Wait for job 1 to complete
2. Queue job 2
3. If need be, have job 2 pause waiting for job 1's outputs to become visible.
4. Allow job 2 to proceed.

I'm not clear on what the advantage of this is over the current state:
1. Wait for job 1's output files to complete.
2. Run job 2
Given that we don't actually care whether or not the job process hangs on exit so long as its outputs have been written and synced, nor do we care if the process terminated if we can't see the files yet.

Is the idea that you want to eat the job queue latency in parallel with waiting on the files to show up?  The risk there is that your job, which may have reserved 20GB of memory and 4 CPU cores, is sitting there doing nothing for a while, which would be wasteful - especially in cases where the job failed silently and never actually wrote its outputs, for example if it got killed by the OOM killer (which ideally would result in the job manager reporting an error state, but not reliably).

Lance says hi back.

**Comment by adam-azarchs** [comment]
One thing I neglected to metion, in cases where there's a dependency martian has to wait on the filesystem regardless, since in order to generate the `_args` for the next stage (or phase) it needs to read the `_outs` of all of that stage's dependencies.

Where such a change could be useful would be when you have a bunch of stages or chunks which do not depend on each other but are throttled by `--maxjobs` (which defaults to 64 because otherwise sysadmins get angry at our customers).  But in those cases you'd do better by just setting `--maxjobs=0` (unlimited) and letting the job queuing system figure out when to schedule stuff.

Of course that's all in cluster mode.  In local mode I've got a fix incoming.
