### ISSUE TITLE
How to debug martian workflow

### ISSUE THREAD

**Issue by Liripo** [martian-lang/martian#148]
Hello: 
As far as I know, other process languages, such as wdl, snakemake, etc., can generate shell scripts for each task, which is convenient for debugging. But how does martain debug the script?

**Comment by adam-azarchs** [comment]
If you are running in cluster mode, martian generates shell scripts (named `_jobscript`) for each job.  It does not generate these in local mode because in that case it's just running the subprocess directly.  If you need this in local mode, martian supports a `--jobmode=fake_remote` mode, intended primarily for testing and debugging martian itself.
